<?php if (cvd_config()->platform()->enabled()) { ?>

<!-- START CONVERDO TRACKING CODE -->
<script type="text/javascript">
    var _paq = _paq || [];
    (function(){
        <?php $this->trackers(); ?>


        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript'; g.defer=true; g.async=true; g.src='<?= cvd_config()->url('tracker.js'); ?>';
        s.parentNode.insertBefore(g,s);
    })();
</script>
<noscript><p><img src="<?= cvd_config()->url('tracker.php'); ?>?idsite=<?= cvd_config()->platform()->website(); ?>" style="border:0" alt="" /></p></noscript>
<!-- END CONVERDO TRACKING CODE -->

<?php $this->debugbar(); ?>
    
<?php } ?>